name: firebase_demo_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  cloud_firestore: ^4.9.1
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  flow_builder: ^0.0.9
  google_fonts: ^4.0.0
  formz: ^0.6.0
  font_awesome_flutter: ^10.1.0 
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.1.13
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
