// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWj7gn40Gh2VAzmS25-Ai-QrNYVl7YdUM',
    appId: '1:1065123101591:web:dbba5da162c40e82f2a2d2',
    messagingSenderId: '1065123101591',
    projectId: 'fir-flutter2023',
    authDomain: 'fir-flutter2023.firebaseapp.com',
    storageBucket: 'fir-flutter2023.appspot.com',
    measurementId: 'G-4F24JNTS3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA1cFJZlPaTqOJwdWPjd4olPqcTNZdyZA',
    appId: '1:1065123101591:android:d51ca33340ef8096f2a2d2',
    messagingSenderId: '1065123101591',
    projectId: 'fir-flutter2023',
    storageBucket: 'fir-flutter2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjbM_Kf76czii22STuXEljiKX3Nggpdgg',
    appId: '1:1065123101591:ios:86d62eb1267c4461f2a2d2',
    messagingSenderId: '1065123101591',
    projectId: 'fir-flutter2023',
    storageBucket: 'fir-flutter2023.appspot.com',
    iosBundleId: 'com.example.firebaseDemoApp',
  );
}
